- requirements.txt
added the requirements.txt file
> Added requirements.txt 

- recorder.py
- ui.py
added browse button for user to select directory to store into 
this is how it looks
> adding browse option to gui

- recorder.py
- ui.py
This PR adds a hotkeys feature to improve navigation within the app (issue #16 ). User's can now use **keys: s, x, t** for starting the **recording, stopping the recording and transcribing the audio respectively**. I have also added the markings that tell the user about these specific hotkeys and increased the window length(ui.py line 40) so that these markings are visible (ui.py line 78-86). I have tested these changes many times to make sure that they are working well. Let me know if any changes are required.
> Implemented Hotkeys

- progress indicator.py
This is a real-time audio recorder and transcriber application built using Python. It leverages the Tkinter library for the graphical user interface (GUI), PyAudio for real-time audio recording, and Whisper AI for transcribing the recorded audio into text. The application allows users to record their voice, save the audio as a .wav file, and transcribe the audio into text with the help of Whisper, an advanced speech-to-text model developed by OpenAI.
>  progress indicator.py

- audio_recorder.py
Description
This pull request introduces a new feature to the application that allows users to record audio, transcribe it using the Whisper model, and display the transcription in a real-time Tkinter GUI. The user can specify the recording duration, and the progress bar at the bottom of the window will update as the audio is being recorded. After recording, the audio is transcribed into text using OpenAI's Whisper model, and the transcription is displayed in a text box for the user.
Key features of this update:
Audio Recording: The application can record audio via the microphone for a user-specified duration.
Progress Bar: A progress bar that dynamically updates during the recording process to show the progress in real-time.
Whisper Integration: The recorded audio is transcribed into …
> audio_recorder.py

- recorder.py
- ui.py
This PR fixes Issue #9 and closes it.
Simply added more precise error handling and logging of issues
> added error handling in recorder

- requirements.txt
- transcriber.py
- Added librosa library for improved audio file handling
- Enhanced audio preprocessing for Whisper model compatibility
- Added better error handling and logging in transcriber.py
- Audio is now loaded using librosa.load() with proper parameters:
- Sample rate: 16kHz (Whisper requirement)
- Mono channel conversion
- Float32 data type conversion
- Added explicit file existence checks
- Improved error messages and logging for better debugging
The changes have been tested with:
- Audio recording and playback
- Transcription of recorded audio
- Error handling for missing files
- More reliable audio file processing
- Better error messages for troubleshooting
- Consistent audio format for Whisper model
- librosa (added to requirements.txt)
> feat: Fix Audio Transcription Issues Using Librosa

- recorder.py
- transcriber.py
- ui.py
This PR attemps to fix #9 . Previous PR #52. Reference #45
> added comprehensive error handling

- recorder.py
- transcriber.py
- ui.py
Reverts CowTheGreat/Real-Time-Audio-Recorder-and-Transcriber-using-Whisper-AI#53
> Revert "added comprehensive error handling"

- .gitignore
- requirements.txt
- text_processor.py
- ui.py
Added new features to summarize transcriptions and ask questions about them using Google's Gemini API.
- Added text summarization capability
- Added ability to query transcribed content
- Added secure API key management using environment variables
- Updated UI with new buttons for summarize and query features
- Added new dependencies (google-generativeai and python-dotenv)
1. Create a `.env` file from `.env.example` and add your Gemini API key
2. After transcribing audio, use the new "Summarize" button to get a concise summary
3. Use the "Ask Question" button to query specific information from the transcription
- API key is managed securely using environment variables
- `.env` file is excluded from git to prevent exposing sensitive information
> Add text summarization and query feature using Gemini API

- requirements.txt
- ui.py
#14 
just drag n drop the file over to drag n drop zone
> added support for drag n drop

- output_transcription_detailed.txt
- transcriber.py
> added confidence to different file 

- transcriber.py
Reverts CowTheGreat/Real-Time-Audio-Recorder-and-Transcriber-using-Whisper-AI#61
> Revert "added confidence to different file "

- transcriber.py
Created a function that appends the transcription to a file named history.txt where the transcription will be kept on updating as we do it, we can use this to know how much entire transcription has been done till now by all of us
> function to append the transcription to a file

- transcriber.py
- ui.py
Fixes and Closes the issue : #4 
- Added dropdown menu to select from 5 Whisper models:
- tiny
- base
- small
- medium
- large
- Implemented lazy loading of models for better UI responsiveness
- Added progress feedback during model loading and transcription
- Updated .gitignore to exclude generated files
- Tested model selection with all 5 models
- Verified lazy loading behavior
- Confirmed proper error handling
- Checked that generated files are properly ignored
> feat: Add Whisper model selection feature

- transcriber.py
- ui.py
Reverts CowTheGreat/Real-Time-Audio-Recorder-and-Transcriber-using-Whisper-AI#66
> Revert "feat: Add Whisper model selection feature"

- ui.py
Added real time waveform visualization (issue #10 ). I've made a **new class of WaveformVisualization in ui.py** . To keep the layout appealing I also decided to **edit the geometry and the way the buttons were placed**. The visualizer is working fine and I have also tested the functionality of the other buttons which are also working as intended. I did encounter a **bug with the "analyze emotion (E)"** button where pressing the button leads to the program entering a buffering state and the error message: "python has stopped responding" I would suggest looking into this however I don't think this issue arises due to changes that have been made by me. This could also just be a bug on my system but if that's not the case then it would be better for us to try and fix it. Let me know if any …
> Real Time Waveform Visualization (issue #10)

- ui.py
Closes : #75 
**Title:**  
🔧 Allow users to annotate transcriptions with comments or notes and save it in a new file.
**Description:**
This PR introduces a new Annotation Feature for transcriptions, allowing users to:
✅ **Add comments** to each transcription.
✅ **Automatically create a new annotation file** for each transcription.
✅ **Add new comments to the same file** instead of overwriting for same transcription
✅ Ensure transcriptions and comments are saved together for future reference.
**Changes Made:**
> ui.py :
- Added an "Annotate Transcription" button.
- Created a new annotation window to view the transcription and add comments.
- Implemented open_annotation_window() to write and save comments with transcription.
- Used MD5 hashing to ensure each transcription gets a unique …
> Add Transcription Annotation Feature ( Issue #75 )

- recorder.py
- ui.py
A few changes to recorder.py and ui.py that display the words per second below the confidence score in the transcription box (issue #73 )
> calculated words per second (issue #73)

- ui.py
Closes: #76 
- Implemented a new dashboard for usage statistics.
- Displays total transcriptions, word counts, and trends.
- Includes bar charts, pie charts, histograms, and line graphs.
- Improved UI with a clean, structured layout.
- Dark theme to match the app UI.
- Left panel: Summary statistics.
- Right panel: Interactive graphs.
- Verified correct data visualization from `history.txt`.
- Tested UI responsiveness and ensured smooth rendering.
- @CowTheGreat  Please review and merge if everything looks good! 🚀
> Added a dashboard to display usage Statistics.

- transcriber.py
- ui.py
Closes: #71 
- Implemented batch processing for multiple audio files.
- All transcriptions are stored in a single file (`batch_transcription.txt`).
- Errors are handled gracefully (corrupt files are skipped).
- Allows users to process multiple files in one go.
- Ensures proper formatting with file-based separation.
- Confidence scores are maintained in a structured format.
- Saves transcriptions efficiently while keeping UI responsive.
- Verified batch processing works correctly with multiple files.
- Checked error handling for missing/corrupt files.
- Ensured UI updates dynamically during batch transcription.
- @CowTheGreat Please review and merge if everything looks good! 🚀
>  Batch Processing for Multiple Audio Files

- requirements.txt
- ui.py
For #74 
Also corrected the requirements file
> Font Size and Colour customization

- .gitignore
- ui.py
> Translate option with  few indian and other languages
